# Generated by Django 3.2.4 on 2021-06-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='calle',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dpto',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numeroCalle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='piso',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoDni',
            field=models.IntegerField(null=True),
        ),
    ]
